### ISSUE TITLE
GitHub Sponsors: Use Entities Listed Under "Sponsor this project"

### ISSUE THREAD

**Issue by jspeed-meyers** [georgetown-cset/funder-finder#15]
From issue #2:

> Another option would be to use whatever entity/entities are listed under "Sponsor this project" on github. Sometimes it's an org (https://github.com/babel/babel), sometimes a person (or multiple people: https://github.com/sindresorhus/got). Mixing the two might make any analysis of funding numbers even trickier, though.

Is this functionality already captured by the code below?

https://github.com/georgetown-cset/funder-finder/blob/c0473c422a5b6ab6312163e77d9c6b32483893bf/funderfinder/utils/github_sources.py#L26-L43

If so, then I could draw on this functionality with a new script? Or is the functionality you reference above separate from that function?

**Comment by jmelot** [comment]
Yep, you could take the list that function returns and then filter to only include github sponsorship links

We may need to filter out (or think carefully about) certain entities though if we go this route, though. For example I just came across [stan](https://github.com/stan-dev/stan) which lists numfocus's github sponsor page!

<img width="357" alt="Screen Shot 2022-12-07 at 4 04 09 PM" src="https://user-images.githubusercontent.com/1252409/206295946-99f77945-be4a-4db9-a7cc-40bde266f776.png">

I can see why they would do that since they're one of the projects sponsored by numfocus, but might lead to misleading conclusions about how much funding this project has
